compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  # offload_optimizer_device: cpu # use cpu
  offload_optimizer_device: cpu # 保留优化器CPU offload（如需进一步降低CPU内存，可切换为 nvme 并配置路径）
  # offload_param_device: cpu # use cpu
  offload_param_device: none # 禁用参数CPU offload，减少CPU内存与拷贝压力
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
